# This workflow will install dependencies, create coverage tests and run Pytest Coverage Comment
# For more information see: https://github.com/MishaKav/pytest-coverage-comment/
name: test branch

on:
  push:
    branches-ignore:
      - "coverage"
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [macos-12, ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    env:
      TZ: 'Asia/Tokyo'
    permissions:
      contents: write
    steps:
      - name: Check is main
        id: is_main
        shell: bash
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ] && [ "${{ matrix.os }}" = "ubuntu-latest" ] && [ "${{ matrix.python-version }}" = "3.12" ];then
            echo "flag=1" >> $GITHUB_OUTPUT
          else
            echo "flag=0" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      - name: Install FFmpeg (macOS)
        if: matrix.os == 'macos-12'
        run: brew install ffmpeg
      - name: Install FFmpeg (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Install poetry
        run: pip install poetry
      - name: Poetry setup
        run: poetry install
      - name: Run test
        id: pytest
        continue-on-error: true
        run: poetry run pytest --durations=0 --junitxml=pytest.xml --cov-report "xml:coverage.xml" --cov=video_grid_merge | tee pytest-coverage.txt
      - name: Pytest coverage comment
        if: ${{ steps.is_main.outputs.flag == '1' }}
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          pytest-xml-coverage-path: ./coverage.xml
          title: Coverage Report
          badge-title: coverage
          hide-badge: false
          hide-report: false
          create-new-comment: false
          hide-comment: false
          report-only-changed-files: false
          remove-link-from-badge: false
          junitxml-path: ./pytest.xml
          junitxml-title: "Pytest Result Summary (os: ubuntu-latest / python-version: 3.12)"
      - name: Update Readme in coverage branch
        if: ${{ steps.is_main.outputs.flag == '1' }}
        run: |
          coverage=$(git branch -a|grep "remotes/origin/coverage$") || :
          if [ -z "$coverage" ];then
            git checkout --orphan coverage
            git rm -rf .
          else
            git checkout coverage
          fi
          commit_hash=${GITHUB_SHA::8}
          commit_link="[$commit_hash](https://github.com/$GITHUB_REPOSITORY/tree/$commit_hash)"
          echo "[![](https://github.com/$GITHUB_REPOSITORY/actions/workflows/test_branch.yml/badge.svg)](https://github.com/$GITHUB_REPOSITORY/actions/workflows/test_branch.yml)" > ./README.md
          echo -e ${{ steps.coverageComment.outputs.summaryReport }} >> ./README.md
          echo -e "> [!Note]" >> ./README.md
          echo -e "> " >> ./README.md
          echo -e "> Commit: $commit_link" >> ./README.md
          echo -e "> " >> ./README.md
          echo "> Click on the `test summary` badge above to see the results of running pytest on multiple hosts." >> ./README.md

      - name: Commit
        if: ${{ steps.is_main.outputs.flag == '1' }}
        run: |
          git config --local user.email "33836132+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update coverage"
      - name: Push
        if: ${{ steps.is_main.outputs.flag == '1' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: coverage
